Hw02
OlgaTikhonchik/nodejs-homework-rest-api pull request #1
Opened 2023-07-12 11:18 UTC by OlgaTikhonchik

Проверьте, пожалуйста!

2023-07-13 07:01 UTC, ceREAL133 requested changes

2023-07-13 07:01 UTC, ceREAL133 commented on app.js
> -})
Delete this comments

2023-07-13 07:01 UTC, ceREAL133 commented on schemas/contactsSchema.js
> +  phone: Joi.string().required(),
You should validate email and phone properly

2023-07-13 08:25 UTC, OlgaTikhonchik commented on app.js
> -})
удалила

2023-07-13 08:47 UTC, OlgaTikhonchik commented on schemas/contactsSchema.js
> +  phone: Joi.string().required(),
добавила проверку

2023-07-14 04:22 UTC, ceREAL133 approved these changes

2023-07-14 08:11 UTC, merged